---
- name: Update Repos Of All Servers
  hosts: all
  tasks:
  - name: update repos
    tags: always
    package: 
      update_cache: yes


- name: Install Apache on web servers
  hosts: web_servers
  roles:
    - web_servers
      

- name: Install db on data base servers
  hosts: database_servers
  roles: 
    - db_servers
