---
- name: Update Repos Of All Servers
  hosts: all
  tasks:
  - name: update repos
    package: 
      update_cache: yes


- name: Install Apache on web servers
  hosts: web_servers
  tasks:
  - name: Install httpd on Alma
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache on Arch
    pacman:
      name: apache
      state: latest
    when: ansible_os_family == "Archlinux"

- name: Install db on data base servers
  hosts: database_servers
  tasks:
  - name: Install mysql on Alma
    dnf:
      name: mysql 
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install mariadb on Arch
    pacman:
      name: mariadb
      state: latest
    when: ansible_os_family == "Archlinux"
