- name: Install httpd on Alma
  tags: alma, httpd, apache
  dnf:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install Apache on Arch
  tags: arch, apache, apache
  pacman:
    name: apache
    state: latest
  when: ansible_os_family == "Archlinux"
